In [1]:
#list 2 dimensi
#list 2 dimensi adalah list di dalam list seperti pada matriks. contoh :
bilangan_genap = [
    [2,4,6,8],
    [10,12,14,16],
    [18,20,22,24],
    [26,28,30,32]
]
print(bilangan_genap)

[[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24], [26, 28, 30, 32]]


In [3]:
#untuk melihat list ketiga bisa menggunakan seperti contoh dibawah ini karena list dihitung mulai dari nol
bilangan_genap[2]

[18, 20, 22, 24]

In [4]:
bilangan_genap[3][2]

# contoh diatas adalah baris ke 4 kolom ke 3 dan ingat list yang dihitung mulai dari nol 

30

In [9]:
bilangan_genap [2][3]=45
print (bilangan_genap[2][3])

#untuk mengganti baris ke 3 dan kolom ke 4 bisa menggunakan contoh seperti di atas

45


In [10]:
bilangan_genap

#jika ingin melihat kembali list yang dikeluarkan maka yang dihasilkan adalah list terbaru yang sudah diganti

[[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 45], [26, 28, 30, 32]]

In [13]:
#untuk menghasilkan isi list yang horisontal bisa gunakan cara di bawah ini
for baris in bilangan_genap:
    print(baris)
#untuk menghasilkan isi list dalam bentuk vertikal
    for kolom in baris:
        print(kolom)
        
#cara di atas adalah untuk memanggil anggota dari list 2 dimensi

[2, 4, 6, 8]
2
4
6
8
[10, 12, 14, 16]
10
12
14
16
[18, 20, 22, 45]
18
20
22
45
[26, 28, 30, 32]
26
28
30
32


In [3]:
#TUPLES
#tuples mirip dengan list tetapi tidak bisa diubah isinya.
#ingat jika masih ingin mengubah isi gunakan list jika tidak gunakan tuples

ganjil = (1,3,5,7,9)

In [4]:
print(ganjil[3])

7


In [5]:
print(ganjil[2:-1])

(5, 7)


In [6]:
for isi in ganjil[1:4]:
    print(isi)

3
5
7


In [7]:
ganjil[0] = 11

TypeError: 'tuple' object does not support item assignment

In [8]:
ganjil.append(11)

AttributeError: 'tuple' object has no attribute 'append'

In [9]:
ganjil.remove(7)

#perubahan list tidak bisa digunakan pada tuples maka dari itu hasilnya akan selalu error jika ingin merubah list

AttributeError: 'tuple' object has no attribute 'remove'

In [10]:
ganjil.count(5)

#perintah ini digunakan untuk menghitung jumlah angka 5 yang ada di list

1

In [11]:
ganjil.index(7)

3

In [12]:
#DICTIONARIES
#dictionaries digunakan jika datanya terkait satu sama lain contoh

data_siswa = {
    "nama" : "hera ana",
    "umur" : 45,
    "apakah_single" : False
}

In [13]:
print(data_siswa["nama"])

hera ana


In [14]:
print(data_siswa["Nama"])

#hasilnya error karena penulisannya salah harusnya nama bukan Nama

KeyError: 'Nama'

In [15]:
print(data_siswa.get("nama"))

hera ana


In [16]:
print(data_siswa.get("Nama"))

None


In [17]:
print(data_siswa.get('tanggal_lahir'))

None


In [18]:
print(data_siswa.get('tanggal_lahir', '12-10-1978'))

12-10-1978


In [19]:
print(data_siswa)

#get digunakan untuk melihat data pada dictionaries saja bukan untuk merubah isi pada dictionaries

{'nama': 'hera ana', 'umur': 45, 'apakah_single': False}


In [20]:
print(data_siswa['tanggal_lahir'])

#karena get digunakan hanya untuk melihat bukan untuk merubah maka jika dicari tidak ada

KeyError: 'tanggal_lahir'

In [21]:
data_siswa['HP'] = '08123456798'

#jika ingin menambahkan kamus gunakan seperti contoh di atas

In [22]:
print(data_siswa['HP'])

08123456798


In [23]:
print(data_siswa)

{'nama': 'hera ana', 'umur': 45, 'apakah_single': False, 'HP': '08123456798'}


In [24]:
#FUNGSI PADA PYTHON

def full_nama(first_name, last_name):
    print(f"nama lengkapnya adalah {first_name} {last_name}")

In [25]:
first_name = input ("nama depan anda adalah ")
last_name = input ("nama belakang anda adalah ")
full_nama(first_name,last_name)

nama depan anda adalah Maria
nama belakang anda adalah Angelina
nama lengkapnya adalah Maria Angelina


In [26]:
#TUGAS FUNGSI PADA PYTHON
#ada 2 jenis fungsi pada python yaitu untuk menjalankan perintah dan menampilkan hasil perhitungan contoh

def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [27]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [28]:
waktu_sampai(40,60)

0.6666666666666666


In [30]:
waktu_tempuh(40,60)

#waktu sampai dan waktu tempuh sama karena perintah yang diberikan sama

0.6666666666666666

In [33]:
a = waktu_sampai(40,60)
print(a)

0.6666666666666666
None


In [34]:
b = waktu_tempuh(40,60)
print (b)

0.6666666666666666


In [35]:
#NUMPY
#numpy memiliki keunggulan dalam perhitungan menggunakan vektor dan matriks dalam berbagai dimensi
#PERINTAH DASAR PADA NUMPY



In [36]:
a = np.array([0,2,4,6,8])
print(a)

[0 2 4 6 8]


In [37]:
b = np.array([[10,12,14,16], [18,20,22,24]])
print(b)

[[10 12 14 16]
 [18 20 22 24]]


In [38]:
c = np.array([[[0,2,4,6],[8,10,12,14]],
            [[16,18,20,22],[24,26,28,30]],
            [[32,34,36,38],[40,42,44,46]]])
print(c)

[[[ 0  2  4  6]
  [ 8 10 12 14]]

 [[16 18 20 22]
  [24 26 28 30]]

 [[32 34 36 38]
  [40 42 44 46]]]


In [39]:
a.ndim

1

In [40]:
b.ndim

2

In [41]:
c.ndim

3

In [42]:
a.shape

(5,)

In [43]:
b.shape

(2, 4)

In [44]:
c.shape

(3, 2, 4)

In [2]:
#MEMANGGIL ANGGOTA, KOLOM DAN BARIS DENGAN NUMPY

import numpy as np

In [3]:
d = np.array([[1,3,5,7], [9,11,13,15], [17,19,21,23]])
print(d)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [4]:
d[0,2]
#untuk memanggil baris pertama kolom ke 3

5

In [5]:
d[2,:]
#untuk memanggil baris ketiga

array([17, 19, 21, 23])

In [6]:
d[:,1]
#untuk memanggil kolom kedua

array([ 3, 11, 19])

In [7]:
d[1,2:3]

array([13])

In [8]:
d[0,2:3]

array([5])

In [9]:
d[1,1:2:3]

array([11])

In [10]:
d[2,2] = 45
print (d)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 45 23]]


In [11]:
#MATRIKS PADA NUMPY
np.ones((4,5))
#untuk membuat matriks yang berisikan angka satu dengan 4 baris dan 5 kolom

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.zeros((3,3))
#untuk membuat matriks yang hanya berisikan bilangan 0 dengan ordo 3x3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,4,6))
#untuk membuat 3 matriks yang hanya berisikan bilangan satu dengan ordo 4x6

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [14]:
np.full((4,3),5)
#untuk membuat matriks dengan bilangan 5 dan ordo 4x3

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
np.random.rand(4,3)
#untuk membuat matriks dengan bilangan yang acak dan ordo 4x3

array([[0.90404702, 0.83732926, 0.85065084],
       [0.68923202, 0.74866346, 0.06525356],
       [0.42181341, 0.47003483, 0.64561504],
       [0.07368617, 0.18685748, 0.8132259 ]])

In [16]:
np.random.randint(1,7, size=(2,3))
#untuk membuat matriks mulai dari bilangan 1 sampai dengan 7 dan ordo 2x3

array([[3, 5, 5],
       [4, 2, 2]])

In [17]:
#CCOPY PADA NUMPY
a = np.array([2,3,5,7,9])
print(a)

[2 3 5 7 9]


In [18]:
b = a
print(b)

[2 3 5 7 9]


In [19]:
b[1]=11
print(b)

[ 2 11  5  7  9]


In [20]:
print(a)
#a ikut berubah karena b = a jadi jika b diganti maka a juga ikut terganti

[ 2 11  5  7  9]


In [21]:
c = np.array([2,3,5,7,9])
print(c)

[2 3 5 7 9]


In [22]:
d = c.copy()
print(d)

[2 3 5 7 9]


In [23]:
d[0]=13
print(d)

[13  3  5  7  9]


In [24]:
print(c)
#c tidak ikut berubah karena d hanya mengkopi dari c dan d tidak sama dengan c

[2 3 5 7 9]


In [25]:
#OPERASI MATEMATIKA PADA NUMPY
#berikut adalah contoh-contoh operasimatematika pada numpy 
a+2

array([ 4, 13,  7,  9, 11])

In [26]:
a-2

array([0, 9, 3, 5, 7])

In [27]:
a*2

array([ 4, 22, 10, 14, 18])

In [28]:
a/2

array([1. , 5.5, 2.5, 3.5, 4.5])

In [29]:
a**2

array([  4, 121,  25,  49,  81], dtype=int32)

In [30]:
b = np.array([12,13,14,15,16])
print(b)

[12 13 14 15 16]


In [31]:
a+b

array([14, 24, 19, 22, 25])

In [32]:
a-b

array([-10,  -2,  -9,  -8,  -7])

In [33]:
a*b

array([ 24, 143,  70, 105, 144])

In [34]:
a/b

array([0.16666667, 0.84615385, 0.35714286, 0.46666667, 0.5625    ])

In [35]:
b**a

array([       144, 1159031605,     537824,  170859375,          0],
      dtype=int32)

In [36]:
np.cos(a)

array([-0.41614684,  0.0044257 ,  0.28366219,  0.75390225, -0.91113026])

In [37]:
np.sin(a)

array([ 0.90929743, -0.99999021, -0.95892427,  0.6569866 ,  0.41211849])

In [38]:
np.tan(a)

array([  -2.18503986, -225.95084645,   -3.38051501,    0.87144798,
         -0.45231566])

In [39]:
np.sinh(a)

array([3.62686041e+00, 2.99370708e+04, 7.42032106e+01, 5.48316123e+02,
       4.05154190e+03])

In [40]:
np.cosh(a)

array([3.76219569e+00, 2.99370709e+04, 7.42099485e+01, 5.48317035e+02,
       4.05154203e+03])

In [41]:
np.tanh(a)

array([0.96402758, 1.        , 0.9999092 , 0.99999834, 0.99999997])

In [42]:
np.sqrt(a)

array([1.41421356, 3.31662479, 2.23606798, 2.64575131, 3.        ])

In [58]:
#PERKALIAN MATRIKS PADA NUMPY
a = np.array([[0,2,4,6],[10,12,14,16]])
print(a)

[[ 0  2  4  6]
 [10 12 14 16]]


In [59]:
b = np.array([[18,20,22,24], [26,28,30,32]])
print(b)

[[18 20 22 24]
 [26 28 30 32]]


In [60]:
c = a*b
print(c)

[[  0  40  88 144]
 [260 336 420 512]]


In [61]:
d = np.matmul(a,b)
#ini tidak bisa karena bentuknya berbeda

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [62]:
e = np.array([[2,4],[6,8],[10,12],[14,16]])
print(e)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [63]:
f = np.matmul(a,e)
print(f)

[[136 160]
 [456 560]]


In [64]:
g = a*e
#ini juga tidak bisa karena bentuknya berbeda

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [65]:
#MIN, MAX DAN SUM PADA NUMPY
a = np.array([[0,2,4,6],
              [10,12,14,16],
              [18,20,22,24]])
print(a)

[[ 0  2  4  6]
 [10 12 14 16]
 [18 20 22 24]]


In [66]:
b = np.min(a)
print(b)

0


In [68]:
c = np.min(a,axis =0)
print (c)
#ini adalah baris terkecil

[0 2 4 6]


In [71]:
d = np.min(a,axis =1)
print(d)
#ini adalah kolom terkecil

[ 0 10 18]


In [70]:
e = np.max(a)
print(e)
#nilai maksimal dari a adalah 24

24


In [72]:
f = np.max(a,axis=0)
print(f)
#ini adalah baris terbesar

[18 20 22 24]


In [73]:
g = np.max(a,axis=1)
print(g)
#ini adalah kolom terbesar

[ 6 16 24]


In [74]:
h = np.sum(a)
print (h)

148


In [75]:
h = np.sum(a,axis=0)
print (h)

[28 34 40 46]


In [76]:
i = np.sum(a,axis=1)
print (i)

[12 52 84]
